### ISSUE TITLE
链接显示了 也能查看到进程 但是不通 跳过tls检测 直接改vps IP地址 均不通

### ISSUE THREAD

**Issue by salehmack** [k0baya/sb-for-serv00#1]
链接显示了 也能查看到进程 但是不通 跳过tls检测 直接改vps IP地址 均不同

**Comment by k0baya** [comment]
请确保你的网络能直连serv00的ssh。不能直连就不能用。

**Comment by salehmack** [comment]
软路由代理环境下不通 warp环境下也测不通 直接使用自定义域名不通 web里ssl显示的两个IP 填写到地址栏 依旧不通

**Comment by k0baya** [comment]
> 软路由代理环境下不通 warp环境下也测不通 直接使用自定义域名不通 web里ssl显示的两个IP 填写到地址栏 依旧不通

你很有想法，不知道谁告诉你可以使用web中ssl的两个IP连接的，本仓库不能这样使用。再次说明，如果你不能直连serv00的ssh（sX.serv00.com），就无法使用此仓库。

**Comment by salehmack** [comment]
top查看进程PID kill pid 结束掉相关进程后 删除生成的sing-box目录 在确认config.json配置正确情况下 重新进入singbox目录执行chmod +x start.sh && bash start.sh 再次显示hy2和tuic5链接
经测已经通了 如果有遇到相似问题的小白 可以借鉴一下 感谢[k0baya](https://github.com/k0baya)

**Comment by k0baya** [comment]
> top查看进程PID kill pid 结束掉相关进程后 删除生成的sing-box目录 在确认config.json配置正确情况下 重新进入singbox目录执行chmod +x start.sh && bash start.sh 再次显示hy2和tuic5链接 经测已经通了 如果有遇到相似问题的小白 可以借鉴一下 感谢[k0baya](https://github.com/k0baya)

你的操作让人有点迷惑，是不是在第一次启动start.sh之后又修改过start.sh？

本仓库的默认工作目录就是在~/sing-box，不管你在哪里运行start.sh，都会在~/sing-box路径下工作。

你说你删掉后重新运行能用，那只有可能是你在首次启动后改过start.sh内的环境变量。

需要修改环境变量的话，就需要把工作目录清空，再重新启动，否则修改不会生效，且会连不上。

**Comment by Davdicten** [comment]
cat: /home/peeter/sing-box/list: No such file or directory 这是怎么回事呢  重复了几次都是这样。

**Comment by k0baya** [comment]
> cat: /home/peeter/sing-box/list: No such file or directory 这是怎么回事呢 重复了几次都是这样。

请确保你的账号下至少有一个 Let‘s Encrypt 证书，不然会拒绝生成配置。

**Comment by Davdicten** [comment]
> > cat： /home/peeter/sing-box/list： 没有这样的文件或目录 这是怎么回事呢 重复了几次都是这样。
> 
> 请确保你的账号下至少有一个 Let's Encrypt 证书，不然会拒绝生成配置。
ssl地址是有一个的Let's Encrypt

**Comment by imbigyellow** [comment]
> > cat: /home/peeter/sing-box/list: No such file or directory 这是怎么回事呢 重复了几次都是这样。
> 
> 请确保你的账号下至少有一个 Let‘s Encrypt 证书，不然会拒绝生成配置。

有证书也会这样，可能是因为程序启动比较慢可能，那边还没生成list文件这边就说没找到了。等几分钟直接在sinbox文件夹里就会出现list文件了

**Comment by k0baya** [comment]
> > > cat: /home/peeter/sing-box/list: No such file or directory 这是怎么回事呢 重复了几次都是这样。
> > 
> > 
> > 请确保你的账号下至少有一个 Let‘s Encrypt 证书，不然会拒绝生成配置。
> 
> 有证书也会这样，可能是因为程序启动比较慢可能，那边还没生成list文件这边就说没找到了。等几分钟直接在sinbox文件夹里就会出现list文件了

正常来说不可能，除非在我指定的工作目录`~/sing-box`以外的地方运行。在`~/sing-box`以外的目录运行，会重新下载需要的所有文件到`~/sing-box`，受限于网速可能会慢。正常按照readme进行，程序启动不到1秒就行。

**Comment by jjyung168** [comment]
> > > cat: /home/peeter/sing-box/list: No such file or directory 这是怎么回事呢 重复了几次都是这样。
> > 
> > 
> > 请确保你的账号下至少有一个 Let‘s Encrypt 证书，不然会拒绝生成配置。
> 
> 有证书也会这样，可能是因为程序启动比较慢可能，那边还没生成list文件这边就说没找到了。等几分钟直接在sinbox文件夹里就会出现list文件了

请问你是怎么等到list文件的  我执行start.sh之后显示没有list  等半天也没有啊 证书也是正常

**Comment by k0baya** [comment]
> > > > cat: /home/peeter/sing-box/list: No such file or directory 这是怎么回事呢 重复了几次都是这样。
> > > 
> > > 
> > > 请确保你的账号下至少有一个 Let‘s Encrypt 证书，不然会拒绝生成配置。
> > 
> > 
> > 有证书也会这样，可能是因为程序启动比较慢可能，那边还没生成list文件这边就说没找到了。等几分钟直接在sinbox文件夹里就会出现list文件了
> 
> 请问你是怎么等到list文件的 我执行start.sh之后显示没有list 等半天也没有啊 证书也是正常

```bash
devil ssl www list | awk '/SNI SSL certificates for WWW/{flag=1; next} flag && NF && $6 != "address" {print $6}' | head -n 1
```

```bash
devil ssl www list | awk '/SNI SSL certificates for WWW/{flag=1; next} flag && NF && $6 != "address" {print $8}' | head -n 1
```

你输入这两条命令能返回什么？

**Comment by jjyung168** [comment]
> > > > > cat: /home/peeter/sing-box/list: No such file or directory 这是怎么回事呢 重复了几次都是这样。
> > > > 
> > > > 
> > > > 请确保你的账号下至少有一个 Let‘s Encrypt 证书，不然会拒绝生成配置。
> > > 
> > > 
> > > 有证书也会这样，可能是因为程序启动比较慢可能，那边还没生成list文件这边就说没找到了。等几分钟直接在sinbox文件夹里就会出现list文件了
> > 
> > 
> > 请问你是怎么等到list文件的 我执行start.sh之后显示没有list 等半天也没有啊 证书也是正常
> 
> ```shell
> devil ssl www list | awk '/SNI SSL certificates for WWW/{flag=1; next} flag && NF && $6 != "address" {print $6}' | head -n 1
> ```
> 
> ```shell
> devil ssl www list | awk '/SNI SSL certificates for WWW/{flag=1; next} flag && NF && $6 != "address" {print $8}' | head -n 1
> ```
> 
> 你输入这两条命令能返回什么？

显示有个邮件 You have new mail in /var/mail/yourname

**Comment by k0baya** [comment]
> > > > > > cat: /home/peeter/sing-box/list: No such file or directory 这是怎么回事呢 重复了几次都是这样。
> > > > > 
> > > > > 
> > > > > 请确保你的账号下至少有一个 Let‘s Encrypt 证书，不然会拒绝生成配置。
> > > > 
> > > > 
> > > > 有证书也会这样，可能是因为程序启动比较慢可能，那边还没生成list文件这边就说没找到了。等几分钟直接在sinbox文件夹里就会出现list文件了
> > > 
> > > 
> > > 请问你是怎么等到list文件的 我执行start.sh之后显示没有list 等半天也没有啊 证书也是正常
> > 
> > 
> > ```shell
> > devil ssl www list | awk '/SNI SSL certificates for WWW/{flag=1; next} flag && NF && $6 != "address" {print $6}' | head -n 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > devil ssl www list | awk '/SNI SSL certificates for WWW/{flag=1; next} flag && NF && $6 != "address" {print $8}' | head -n 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你输入这两条命令能返回什么？
> 
> 显示有个邮件 You have new mail in /var/mail/yourname

请把你输入上述命令的返回结果截图一下。
