### ISSUE TITLE
给出的节点都不能用

### ISSUE THREAD

**Issue by zyrubber** [k0baya/sb-for-serv00#10]
+ 按照教程配置成功了了，也得到  `list` 了，但是所有节点都不通
+ 生成vless节点为什么 `alpn=h3` 阿。
+ 脚本加密了吗？那么能不能给出比较详细文件结构
+ 如何重新布置
+ 如何卸载

**Comment by k0baya** [comment]
...你的问题有很多都是可以自己解决的。

节点通不通的，如果进程确定在运行，还不通就是你自己的客户端或者本地网络问题，我对此无法提供任何帮助。

sing-box 的服务端配置就在你自己的账号里，如果你对于导出的配置有疑问，那你完全可以自己看着服务端配置自己写客户端配置。

脚本经过简单混淆，提高 YouTube 上某些无良博主的抄袭难度，稍微会一点点 shell 就能轻松反混淆。文件结构你问我不如自己去看，面板里有文件管理，ssh 也没有禁止你使用 `ls` 和 `cd` 命令。

全部删掉就可以重新部署了。

至于怎么删除，`/control` 下有 `uninstall` 按钮，你也可以使用一键还原的命令：
```
bash <(curl -Ls https://raw.githubusercontent.com/k0baya/x-for-serv00/main/reset.sh)
```

建议有问题先去找 GPT 问一遍，看看 GPT 在没有任何日志信息、文件信息、进程列表等等信息的情况下能否精准通过算命解决你的疑问。

**Comment by zyrubber** [comment]
感谢回复。我去试试。有不懂，在来请教

**Comment by k0baya** [comment]
> 感谢回复。我去试试。有不懂，在来请教

我的意思是，如果可以，希望你能提供你的账号的进程列表，且邮件给我你的节点链接，测试是否只是你的本地网络/客户端无法使用。

在信息不足的情况下我实在没办法解决你不能用的问题。

**Comment by zyrubber** [comment]
+ 卸载脚本很好用。能reset，可以来回折腾就好办了。
+ 对FreeBSD没接触过。折腾一下主要是为了给自己涨点经验，学习学习。并不是只为了等这个小鸡科学上网。
+ 目录找了，也`ls`了。就是没能找到安装目录，见笑了。所以才来请教目录结构。
+ 折腾这个小鸡的项目挺多。最后找到您的项目准备试一下，是因为多数项目使用的貌似都是自己编译的。希望能够找一个原理透明的，学习一下
+ 再次感谢。懂得分享不易，也希望您的分享能授人以渔，否则就失去了分享意义。

**Comment by k0baya** [comment]
本项目设置的工作目录为：`/home/LOGIN/domains/LOGIN.serv00.net/public_nodejs/`

**Comment by zyrubber** [comment]
找到了。感谢

**Comment by zyrubber** [comment]
```
{
      "type": "vless",
      "tag": "vl-sb",
      "listen": "::",
      "listen_port": 15001,
      "users": [{
        "uuid": "ef03abc6-443e-442f-9864-fc3558481713"
      }],
      "tls": {
        "enabled": true,
        "alpn": [
          "h3"
        ],
        "certificate_path": "/home/aaa/domains/aaaa.serv00.net/public_nodejs/cert.crt",
        "key_path": "/home/aaaa/domains/aaaa.serv00.net/public_nodejs/private.key"
      },
      "multiplex": {
        "enabled": true,
        "padding": false
      },
      "transport": {
        "type": "ws",
        "path": "/serv00-vl",
        "max_early_data": 2560,
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
      }
  ],
```
以上是vless部分的配置文件。我理解alpn不应该是`h3`，客户端报错` remote error: tls: no application protocol`

- 尝试手动改了一下配置文件。但是没有解决问题。
- 因为默认的域名证书申请限制，我通过面板添加的自定义域名
- 其余的安装过程严格按照教程重复了几遍。结果没有变化。

**Comment by k0baya** [comment]
![Screenshot_2024-08-21-11-44-57-75_f31c5faf1ec54ae](https://github.com/user-attachments/assets/44141923-14f9-4803-a21c-07c93c80cc6b)

我之所以这么写配置文件，是因为我这里测试没有问题。对于这个仓库已经自带的东西，比如配置文件什么的，贴出来并不能让我获取到有用的信息。

你不如发一个你的配置链接给我，对比看看是不是你本地网络/客户端有问题。

另外，你确定相关进程已经在运行了？`/status`的进程列表确认过了吗？

**Comment by zyrubber** [comment]
![sta](https://github.com/user-attachments/assets/e6eca7c1-b5e9-45ad-bcd0-8ba5c9e0373b)
我当然知道您在自己那里跑起来没问题。

v2rayN测试，Hysteria2 和 Tuic5真链接有延迟，但是并不能代理。vless为-1。
好了，也耽误了您不少时间。感谢。

**Comment by k0baya** [comment]
要不换个内核版本比较新的客户端试试？
![IMG_20240821_130805](https://github.com/user-attachments/assets/f04cfa74-4dda-4df0-aec5-98d6487119ac)
