### ISSUE TITLE
选择占用端口数

### ISSUE THREAD

**Issue by sunboy0523** [k0baya/sb-for-serv00#11]
谢谢您的分享，能不能自由选择占用端口数，三种singbox支持的协议，其实网速都差不太多，有一个正常就可以，三个端口都占用，就不能部署其它应用了，感觉挺浪费，谢谢

**Comment by k0baya** [comment]
我个人是不太喜欢在脚本内增加太多非必要交互的。如果你对于协议不满意，可以在部署好之后去编辑配置文件并重启。

另外对于占满三个端口这个设计，初衷就是为了让使用本仓库的人拿一个其他任何应用都没有部署的账号来使用。原因如下：

1. 核心占用内存很多。也许你部署完，一看内存根本没用多少，但是在大流量高负载的情况下占用的内存是很多的，如果还要再来一个其它应用抢占内存，容易导致崩溃；
2. 减少用户部署其他应用时对本项目的影响。目前完全是利用 Serv00 做到的保活唤醒，难免用户在部署其他应用时不清楚原理而做出影响本项目的操作，如果因此出现一些问题，不好处理。我相信真的能够避免做出对本项目造成影响的用户，肯定也是能够轻松的在部署完成后手动修改配置文件的。

**Comment by sunboy0523** [comment]
> 我个人是不太喜欢在脚本内增加太多非必要交互的。如果你对于协议不满意，可以在部署好之后去编辑配置文件并重启。
> 
> 另外对于占满三个端口这个设计，初衷就是为了让使用本仓库的人拿一个其他任何应用都没有部署的账号来使用。原因如下：
> 
> 1. 核心占用内存很多。也许你部署完，一看内存根本没用多少，但是在大流量高负载的情况下占用的内存是很多的，如果还要再来一个其它应用抢占内存，容易导致崩溃；
> 2. 减少用户部署其他应用时对本项目的影响。目前完全是利用 Serv00 做到的保活唤醒，难免用户在部署其他应用时不清楚原理而做出影响本项目的操作，如果因此出现一些问题，不好处理。我相信真的能够避免做出对本项目造成影响的用户，肯定也是能够轻松的在部署完成后手动修改配置文件的。

谢谢，从您明码脚本一路更新过来的，所以也能修改加密代码配制后的节点，但如果先占用一个端口部署了其它应用比如alist，脚本就会因为端口不够而执行失败。我是因为尝试您博文的保活方案，但npm22执行安装一直失败，提示“npm http fetch GET https://registry.npmjs.org/express attempt 1 failed with ETIMEDOUT
npm http fetch GET https://registry.npmjs.org/express attempt 2 failed with ETIMEDOUT
npm http fetch GET 200 https://registry.npmjs.org/express 595448ms (cache revalidated)”这些内容，ping了registry.npmjs.org这个站点，又没有问题。所以想试试您的这个库能不能成功，但我原来部署alist用了一个端口。
