### ISSUE TITLE
修改app.js文件为保活多个程序后，怎样重新启动app.js

### ISSUE THREAD

**Issue by sunboy0523** [k0baya/sb-for-serv00#13]
非常感谢您分享原创作品

总算在GPT的帮助下成功修改app.js为保活多个进程，请问怎么重启app.js ？
我把node22进程终止，运行node app.js报错，重新用您的脚本不删除文件跑一遍（不会删除我修改后的app.js，只会重新生成节点的配置），可以正常启动app.js ，也可以保活我添加监控的进程。请问用什么命令重新启动修改后的app.js 。谢谢

**Comment by k0baya** [comment]
`killall -u $(whoami)` 杀掉一切进程，然后直接访问网址就能启动 `app.js`。不需要你执行什么命令。

**Comment by sunboy0523** [comment]
> `killall -u $(whoami)` 杀掉一切进程，然后直接访问网址就能启动 `app.js`。不需要你执行什么命令。

谢谢
