### ISSUE TITLE
正在生成配置持续了两个小时，如何卸载重来？

### ISSUE THREAD

**Issue by bojur00** [k0baya/sb-for-serv00#14]
按照步骤走完了流程，最后下载singbox，然后生成配置，生成了两个多小时都没有进展，如何卸载重来？

**Comment by k0baya** [comment]
你这个情况要么是密码输错了，要么是没有证书。
使用以下命令重置：
```
bash <(curl -Ls https://raw.githubusercontent.com/k0baya/x-for-serv00/main/reset.sh)
```

**Comment by bojur00** [comment]
是没有证书，没注意到有前提条件，我试下重置

**Comment by bojur00** [comment]
已经添加了自己的域名，并且生成了证书，重置过后重走流程，还是显示正在尝试生成配置...，两个singbox的脚本都试过了，结果都相同，求解惑

**Comment by k0baya** [comment]
> 你这个情况要么是密码输错了，要么是没有证书。

密码是你的 Serv00 账号的密码，即你在登录 Panel 以及 SSH 时使用的密码。你可以直接复制粘贴的。
