### ISSUE TITLE
如何用自己的域名安装

### ISSUE THREAD

**Issue by ycfriend** [k0baya/sb-for-serv00#18]
自己的域名解析正常，并在面板里生成了Let's Encrypt的证书，已删除原有serv00.net的域名，但脚本还是用原有serv00.net的域名进行安装，最后提示证书获取失败。

**Comment by k0baya** [comment]
请检查密码输入是否正确。

**Comment by KisThFir** [comment]
@k0baya 佬，serv00的域名被墙了，如何无需重新部署更换自己的域名呢？

**Comment by k0baya** [comment]
> @k0baya 佬，serv00的域名被墙了，如何无需重新部署更换自己的域名呢？

如果是域名被墙，可以把直连接入点（webX.serv00.com、cacheX.serv00.com、sX.serv0.com）的 IP 分别用自己的域名添加 DNS 记录 A 类型指向，然后替换客户端配置中的相应配置。

如果是端口被墙，可以尝试完全卸载并删除所有端口，然后重新部署。

如果是 IP 被墙，就只能使用 Cloudflare CDN 的接入方式了。

你得根据实际情况进行选择，但是至少，只要 Cloudflare CDN 不被墙，那么使用其连入的方式就永远不会被墙。

**Comment by ycfriend** [comment]
> 请检查密码输入是否正确。

确实密码问题，但还是会安装到默认域名的文件夹。因为默认域名的ip已被墙，所以只能用自己域名指向第2个ip，目前只能把安装后文件拷贝到自己域名的文件夹中来使用。
另外hy2似乎不能使用ssl中给的两个ip，只能用s**.serv00.com这个ip，有没有办法解决。

**Comment by k0baya** [comment]
> > 请检查密码输入是否正确。
> 
> 确实密码问题，但还是会安装到默认域名的文件夹。因为默认域名的ip已被墙，所以只能用自己域名指向第2个ip，目前只能把安装后文件拷贝到自己域名的文件夹中来使用。 另外hy2似乎不能使用ssl中给的两个ip，只能用s**.serv00.com这个ip，有没有办法解决。

获取代理配置的域名和代理连入的域名是两回事，你为什么要执着于把这个获取代理配置的页面部署在自己的域名下？基于 UDP 连接的协议必须使用 sX.serv00.com 的 IP，是 serv00 主机的路由问题导致的，解决办法我给不了，你得去找 serv00 的运营方解决。

**Comment by ycfriend** [comment]
> > > 请检查密码输入是否正确。
> > 
> > 
> > 确实密码问题，但还是会安装到默认域名的文件夹。因为默认域名的ip已被墙，所以只能用自己域名指向第2个ip，目前只能把安装后文件拷贝到自己域名的文件夹中来使用。 另外hy2似乎不能使用ssl中给的两个ip，只能用s**.serv00.com这个ip，有没有办法解决。
> 
> 获取代理配置的域名和代理连入的域名是两回事，你为什么要执着于把这个获取代理配置的页面部署在自己的域名下？基于 UDP 连接的协议必须使用 sX.serv00.com 的 IP，是 serv00 主机的路由问题导致的，解决办法我给不了，你得去找 serv00 的运营方解决。

好吧，感谢大佬

**Comment by kentcc88** [comment]
> > @k0baya 佬，serv00的域名被墙了，如何无需重新部署更换自己的域名呢？
> 
> 如果是域名被墙，可以把直连接入点（webX.serv00.com、cacheX.serv00.com、sX.serv0.com）的 IP 分别用自己的域名添加 DNS 记录 A 类型指向，然后替换客户端配置中的相应配置。
> 
> 如果是端口被墙，可以尝试完全卸载并删除所有端口，然后重新部署。
> 
> 如果是 IP 被墙，就只能使用 Cloudflare CDN 的接入方式了。
> 
> 你得根据实际情况进行选择，但是至少，只要 Cloudflare CDN 不被墙，那么使用其连入的方式就永远不会被墙。

我的是IP被墙，使用cloudflare CDN好像也救不活

**Comment by k0baya** [comment]
> > > @k0baya 佬，serv00的域名被墙了，如何无需重新部署更换自己的域名呢？
> > 
> > 
> > 如果是域名被墙，可以把直连接入点（webX.serv00.com、cacheX.serv00.com、sX.serv0.com）的 IP 分别用自己的域名添加 DNS 记录 A 类型指向，然后替换客户端配置中的相应配置。
> > 如果是端口被墙，可以尝试完全卸载并删除所有端口，然后重新部署。
> > 如果是 IP 被墙，就只能使用 Cloudflare CDN 的接入方式了。
> > 你得根据实际情况进行选择，但是至少，只要 Cloudflare CDN 不被墙，那么使用其连入的方式就永远不会被墙。
> 
> 我的是IP被墙，使用cloudflare CDN好像也救不活

如果你所在的地区连 cloudflare 都被墙了，建议你放弃使用本仓库。
