### ISSUE TITLE
似乎不能搭建

### ISSUE THREAD

**Issue by taiyi747** [k0baya/sb-for-serv00#2]
SB-for-Serv00 is trying to start up, please waiting...
cat: /home/xxxxx/sing-box/list: No such file or directory

**Comment by k0baya** [comment]
请保证你的账号下有一个Let's Encrypt证书，否则会拒绝生成配置。参考[#1 ](https://github.com/k0baya/sb-for-serv00/issues/1)下的回复。

**Comment by taiyi747** [comment]
看了一下，serv00这个号这周不让开ssl难受

**Comment by taiyi747** [comment]
The weekly certificate limit for the domain has been used
好像确实不行，他们家限制域名ssl申请了

**Comment by k0baya** [comment]
> The weekly certificate limit for the domain has been used 好像确实不行，他们家限制域名ssl申请了

一直都有每周上限，要么抢名额，要么自己把代码改改生成不带sni的配置，为确保安全，本仓库不会提供不安全的配置，有需求请自己改。
