### ISSUE TITLE
能不能想办法利用s00的第二个IP

### ISSUE THREAD

**Issue by bbylw** [k0baya/sb-for-serv00#20]
第一个IP基本都墙了，第二个IP不少还活着呢

**Comment by k0baya** [comment]
不知道你用的哪个分支。能用的 IP，仓库里肯定是一个不差的全部用上了。

具体参考我在 [#18](https://github.com/k0baya/sb-for-serv00/issues/18#issuecomment-2351900491) 以及 [#8](https://github.com/k0baya/sb-for-serv00/issues/8#issuecomment-2275808811) 中我的回复。
