### ISSUE TITLE
生成6个节点，却只有2个通的

### ISSUE THREAD

**Issue by kentcc88** [k0baya/sb-for-serv00#21]
一共生成了6个节点，但通的只有cache*和upos*这两个节点，其他节点不通。。我试着ping了下节点配置的s12和web12域名，是不通的，有没有人遇到和我一样的情况？请教是哪里出问题了？

**Comment by k0baya** [comment]
说明 `sX` 和 `webX` 在你的网络环境下被墙。
请参考 [#18](https://github.com/k0baya/sb-for-serv00/issues/18#issuecomment-2351900491) 中我的回复。

**Comment by kentcc88** [comment]
> 说明 `sX` 和 `webX` 在你的网络环境下被墙。 请参考 [#18](https://github.com/k0baya/sb-for-serv00/issues/18#issuecomment-2351900491) 中我的回复。

好的，谢谢大佬指点
