### ISSUE TITLE
正常配置后三个vless节点无法连通

### ISSUE THREAD

**Issue by Gurosuogen** [k0baya/sb-for-serv00#22]
大佬你好，客户端使用的是 Clash Verge Rev ，核心是 mihomo ，部署在 s7 上
s7 / cache7 / web7 三个 vless 节点都无法连通
在我的本地直接 ping 这三个域名都是能直接 ping 通的
不知道问题出在了哪里

**Comment by k0baya** [comment]
我也不知道

**Comment by bbylw3** [comment]
多试几个客户端

**Comment by Gurosuogen** [comment]
感谢回复，我自己慢慢折腾吧

**Comment by Gurosuogen** [comment]
根据抄来的 `Vless-Reality-Vision` 配置，最后连通成功，在这里分享下
```json
        {
            "type": "vless",
            "tag": "vlv-sb",
            "listen": "::",
            "listen_port": " 面板中放行的 TCP 端口 ",
            "sniff": true,
            "sniff_override_destination": true,
            "users": [
                {
                    "uuid": " 自己生成 UUID ",
                    "flow": "xtls-rprx-vision"
                }
            ],
            "tls": {
                "enabled": true,
                "server_name": "icloud.cdn-apple.com",
                "reality": {
                    "enabled": true,
                    "handshake": {
                        "server": "icloud.cdn-apple.com",
                        "server_port": 443
                    },
                    "private_key": " 填入sing-box 生成的 reality key ",
                    "short_id": [
                    ""
                ]
                }
            },
            "multiplex": {
                "enabled": true,
                "padding": true
            }
        }
```

**Comment by k0baya** [comment]
reality 不支持套 cdn，需要使用 reality，可以使用现成的另外一个库：
https://github.com/k0baya/X-for-serv00/tree/direct
![image](https://github.com/user-attachments/assets/0a4ce326-87fc-4fb7-8cab-54797c4fba4d)

**Comment by Gurosuogen** [comment]
> reality 不支持套 cdn，需要使用 reality，可以使用现成的另外一个库： https://github.com/k0baya/X-for-serv00/tree/direct ![image](https://private-user-images.githubusercontent.com/132335755/371907657-0a4ce326-87fc-4fb7-8cab-54797c4fba4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MjI0NTEsIm5iZiI6MTcyNzcyMjE1MSwicGF0aCI6Ii8xMzIzMzU3NTUvMzcxOTA3NjU3LTBhNGNlMzI2LTg3ZmMtNGZiNy04Y2FiLTU0Nzk3YzRmYmE0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxODQ5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDg0NWUyMzQzZDUyNzM3Zjg4MzQyODA0YmM5OTM4YjgxYjNmMGJmMmFkNWEzMzZmYTY4MzQwZmNkYmY1OTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._S3LT1aXk9uQH93cYM1_AbsQUucafXStakhDtBPYtmI)

大佬你的库里没找到 `config.json` 应该是加密了，能不能让我看看配置，我抄抄看

**Comment by k0baya** [comment]
> > reality 不支持套 cdn，需要使用 reality，可以使用现成的另外一个库： https://github.com/k0baya/X-for-serv00/tree/direct ![image](https://private-user-images.githubusercontent.com/132335755/371907657-0a4ce326-87fc-4fb7-8cab-54797c4fba4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MjI0NTEsIm5iZiI6MTcyNzcyMjE1MSwicGF0aCI6Ii8xMzIzMzU3NTUvMzcxOTA3NjU3LTBhNGNlMzI2LTg3ZmMtNGZiNy04Y2FiLTU0Nzk3YzRmYmE0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxODQ5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDg0NWUyMzQzZDUyNzM3Zjg4MzQyODA0YmM5OTM4YjgxYjNmMGJmMmFkNWEzMzZmYTY4MzQwZmNkYmY1OTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._S3LT1aXk9uQH93cYM1_AbsQUucafXStakhDtBPYtmI)
> 
> 大佬你的库里没找到 `config.json` 应该是加密了，能不能让我看看配置，我抄抄看

你跑一遍安装脚本即可在工作目录找到配置文件。

**Comment by Gurosuogen** [comment]
> > > reality 不支持套 cdn，需要使用 reality，可以使用现成的另外一个库： https://github.com/k0baya/X-for-serv00/tree/direct ![image](https://private-user-images.githubusercontent.com/132335755/371907657-0a4ce326-87fc-4fb7-8cab-54797c4fba4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MjI0NTEsIm5iZiI6MTcyNzcyMjE1MSwicGF0aCI6Ii8xMzIzMzU3NTUvMzcxOTA3NjU3LTBhNGNlMzI2LTg3ZmMtNGZiNy04Y2FiLTU0Nzk3YzRmYmE0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxODQ5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDg0NWUyMzQzZDUyNzM3Zjg4MzQyODA0YmM5OTM4YjgxYjNmMGJmMmFkNWEzMzZmYTY4MzQwZmNkYmY1OTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._S3LT1aXk9uQH93cYM1_AbsQUucafXStakhDtBPYtmI)
> > 
> > 
> > 大佬你的库里没找到 `config.json` 应该是加密了，能不能让我看看配置，我抄抄看
> 
> 你跑一遍安装脚本即可在工作目录找到配置文件。

好的，感谢大佬
