### ISSUE TITLE
能增加一个SOCKS5版本吗

### ISSUE THREAD

**Issue by bbylw3** [k0baya/sb-for-serv00#24]
SOCKS5 套CF，无论IP墙不墙都可以用来访问chatgpt，太需要了

**Comment by k0baya** [comment]
配置上的特殊需求，你可以自己修改安装完毕后的 sing-box 配置文件来实现，我不可能也没办法满足所有人的需求。配置文件在 `/home/LOGIN/domains/LOGIN.serv00.net/public _nodejs/config.json`
请参照 sing-box 官方文档：
https://sing-box.sagernet.org/zh/configuration/
