### ISSUE TITLE
域名被墙是不是就没办法用了

### ISSUE THREAD

**Issue by zyhiderole** [k0baya/sb-for-serv00#26]
直接pings11.server.com  ping不通是不是就没办法用？我试了下 cf cname到这个地址 开代理 好像也不行。还有啥办法吗？

**Comment by k0baya** [comment]
#18 
![image](https://github.com/user-attachments/assets/bcb4793b-15d7-41bb-850f-a62a014981d6)

**Comment by zyhiderole** [comment]
> #18 ![image](https://private-user-images.githubusercontent.com/132335755/376147380-bcb4793b-15d7-41bb-850f-a62a014981d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDM0MTEsIm5iZiI6MTcyODkwMzExMSwicGF0aCI6Ii8xMzIzMzU3NTUvMzc2MTQ3MzgwLWJjYjQ3OTNiLTE1ZDctNDFiYi04NTBmLWE2MmEwMTQ5ODFkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMDUxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2JhN2YwZTc2Y2ZmZmIzM2Y1NGQyMTFjYjIzNTNlZDMwNDVlNjU3MTBhOGYzYzcwYTUxMWY4ZmNjNmM2OWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qqSAjbjn7hFINQefvR59OdFwXuAUZaK2WKsbIYJRwI4)
查了下 hy2的协议 不支持 套cdn 我还是装v2ray吧
