### ISSUE TITLE
还不支持ct8

### ISSUE THREAD

**Issue by flypig2025** [k0baya/sb-for-serv00#4]
已经获取证书，按照教程启动时提示没有list.

**Comment by k0baya** [comment]
![image](https://github.com/user-attachments/assets/6914a84a-868b-49d1-abf0-7edd26c45edd)
无法复现，请确定你确实获取到了证书，且启动脚本内的账户密码填写正确。
另，ct8 的 udp 流量已经被 gfw 阻断，请确保使用时不在中国大陆，否则连不上。

**Comment by flypig2025** [comment]
密码检查了一下，复制过去的，没缺少或增加字符，也没有空格，填写在半角单引号内

> ![image](https://private-user-images.githubusercontent.com/132335755/350218964-6914a84a-868b-49d1-abf0-7edd26c45edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjA3MjAsIm5iZiI6MTcyMTM2MDQyMCwicGF0aCI6Ii8xMzIzMzU3NTUvMzUwMjE4OTY0LTY5MTRhODRhLTg2OGItNDlkMS1hYmYwLTdlZGQyNmM0NWVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMzQwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjI5YzkxYmMwOTA4YzNkM2I3ZTVlYmY3YzhmMjk2ZGRiMTQ4MTJmYjFhYzAxNzY2ZjFkYTAwZTBkMGI0ODA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a5qiNMil5nR-QSvU0yZLAyGrKx2Pur1tQJOp98mOYxM) 无法复现，请确定你确实获取到了证书，且启动脚本内的账户密码填写正确。 另，ct8 的 udp 流量已经被 gfw 阻断，请确保使用时不在中国大陆，否则连不上。

大佬，证书确实已经获取，密码检查了一下，复制过去的，没缺少或增加字符，也没有空格，填写在半角单引号内，是不是不需要半角单引号？

**Comment by k0baya** [comment]
> 密码检查了一下，复制过去的，没缺少或增加字符，也没有空格，填写在半角单引号内
> 
> > ![image](https://private-user-images.githubusercontent.com/132335755/350218964-6914a84a-868b-49d1-abf0-7edd26c45edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjA3MjAsIm5iZiI6MTcyMTM2MDQyMCwicGF0aCI6Ii8xMzIzMzU3NTUvMzUwMjE4OTY0LTY5MTRhODRhLTg2OGItNDlkMS1hYmYwLTdlZGQyNmM0NWVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMzQwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjI5YzkxYmMwOTA4YzNkM2I3ZTVlYmY3YzhmMjk2ZGRiMTQ4MTJmYjFhYzAxNzY2ZjFkYTAwZTBkMGI0ODA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a5qiNMil5nR-QSvU0yZLAyGrKx2Pur1tQJOp98mOYxM) 无法复现，请确定你确实获取到了证书，且启动脚本内的账户密码填写正确。 另，ct8 的 udp 流量已经被 gfw 阻断，请确保使用时不在中国大陆，否则连不上。
> 
> 大佬，证书确实已经获取，密码检查了一下，复制过去的，没缺少或增加字符，也没有空格，填写在半角单引号内，是不是不需要半角单引号？

```bash
devil ssl www list | awk '/SNI SSL certificates for WWW/{flag=1; next} flag && NF && $6 != "address" {print $6}' | head -n 1
```

```bash
devil ssl www list | awk '/SNI SSL certificates for WWW/{flag=1; next} flag && NF && $6 != "address" {print $8}' | head -n 1
```

试一下这两条命令分别返回什么。

**Comment by jjyung168** [comment]
> > 密码检查了一下，复制过去的，没缺少或增加字符，也没有空格，填写在半角单引号内
> > > ![image](https://private-user-images.githubusercontent.com/132335755/350218964-6914a84a-868b-49d1-abf0-7edd26c45edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjA3MjAsIm5iZiI6MTcyMTM2MDQyMCwicGF0aCI6Ii8xMzIzMzU3NTUvMzUwMjE4OTY0LTY5MTRhODRhLTg2OGItNDlkMS1hYmYwLTdlZGQyNmM0NWVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMzQwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjI5YzkxYmMwOTA4YzNkM2I3ZTVlYmY3YzhmMjk2ZGRiMTQ4MTJmYjFhYzAxNzY2ZjFkYTAwZTBkMGI0ODA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a5qiNMil5nR-QSvU0yZLAyGrKx2Pur1tQJOp98mOYxM) 无法复现，请确定你确实获取到了证书，且启动脚本内的账户密码填写正确。 另，ct8 的 udp 流量已经被 gfw 阻断，请确保使用时不在中国大陆，否则连不上。
> > 
> > 
> > 大佬，证书确实已经获取，密码检查了一下，复制过去的，没缺少或增加字符，也没有空格，填写在半角单引号内，是不是不需要半角单引号？
> 
> ```shell
> devil ssl www list | awk '/SNI SSL certificates for WWW/{flag=1; next} flag && NF && $6 != "address" {print $6}' | head -n 1
> ```
> 
> ```shell
> devil ssl www list | awk '/SNI SSL certificates for WWW/{flag=1; next} flag && NF && $6 != "address" {print $8}' | head -n 1
> ```
> 
> 试一下这两条命令分别返回什么。

我也是提示这个cat: /home//sing-box/list: No such file or directory 

执行这两条命令什么也没返回

**Comment by flypig2025** [comment]
都返回空值呢
![屏幕截图 2024-07-23 185439](https://github.com/user-attachments/assets/5cd8bfcf-a1c1-4a0c-9d66-7cefb5e02a05)

**Comment by flypig2025** [comment]
大佬，请看截图
![屏幕截图 2024-07-23 191139](https://github.com/user-attachments/assets/a21f6c58-0a21-4c9a-b4b9-f4110770f021)

**Comment by k0baya** [comment]
> 大佬，请看截图 ![屏幕截图 2024-07-23 191139](https://private-user-images.githubusercontent.com/175516598/351302137-a21f6c58-0a21-4c9a-b4b9-f4110770f021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzU0ODYsIm5iZiI6MTcyMTczNTE4NiwicGF0aCI6Ii8xNzU1MTY1OTgvMzUxMzAyMTM3LWEyMWY2YzU4LTBhMjEtNGM5YS1iNGI5LWY0MTEwNzcwZjAyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxMTQ2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODVmOGRlNzBhYjhiMDk4ZmIzOWVjN2ZiOTQyN2E1NDc1YTY4NDBjM2FiOWRjZTdjYzNjZjQ1Yzk2NjllZWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3V8spDlZE3B5oELfMPA4KHe09IzfliJLskX85MAM5f8)

线程数超出限制了。请反复执行`killall -u $(whoami)`直到你的ssh被断开，再重新ssh登入启动。

**Comment by ychappyman** [comment]
大佬，清理后再ssh进去执行这两条命令无响应，执行bash start.sh提示如下chmod +x start.sh && bash start.sh
SB-for-Serv00 is trying to start up, please waiting...
cat: /home/maxjiu/sing-box/list: No such file or directory

**Comment by k0baya** [comment]
> 大佬，清理后再ssh进去执行这两条命令无响应，执行bash start.sh提示如下chmod +x start.sh && bash start.sh SB-for-Serv00 is trying to start up, please waiting... cat: /home/maxjiu/sing-box/list: No such file or directory

说明你账号内没有Let's Encrypt证书。

**Comment by k0baya** [comment]
请好好阅读 README，总共也没多长。你看漏的部分在这里：

>然后是最重要的部分，生成一个 Let's Encrypted 证书：
>
>在 Panel 中点击左侧菜单栏中的 SSL ，然后点击上方菜单栏中的 WWW websites ，点击第一个 IP Address 最右侧的 Manage 按钮，再点击上方菜单栏中的 Add certificate 按钮，Type 选择 Generate Let's Encrypt certificate， Domain任选一个即可，最后点击下方的 Add 按钮进行生成。请至少保证自己的 Serv00 账号下有一个 Let's Encrypt 的证书。

没有证书就会中途退出，拒绝生成配置，故意这么写的。

**Comment by ychappyman** [comment]
确实已经生成了呢
![mmexport1721739043505](https://github.com/user-attachments/assets/1eef94e2-8a3c-48e2-ba75-745aa0baae95)
![mmexport1721739041231](https://github.com/user-attachments/assets/227fa95f-b5a4-4061-bcca-d30e662df46a)
![mmexport1721739045797](https://github.com/user-attachments/assets/504a0502-b2d3-4732-a0f2-8873fa640f3f)
![mmexport1721739038660](https://github.com/user-attachments/assets/21764d33-90aa-4af6-87ee-905b7f0c9006)

**Comment by k0baya** [comment]
那就，执行以下这个命令，截图我看看返回结果：
```
devil ssl www list
```

一般有证书的话，这两条命令能返回证书对应的IP和域名：
![image](https://github.com/user-attachments/assets/7d46f7bb-63c6-40df-ae6f-ea9e1abd09e0)

**Comment by flypig2025** [comment]
返回结果如下：
![微信图片_20240724101626](https://github.com/user-attachments/assets/f797418d-1768-4a2c-99b8-88b26f78ad81)

**Comment by k0baya** [comment]
> 返回结果如下： ![微信图片_20240724101626](https://private-user-images.githubusercontent.com/175516598/351551821-f797418d-1768-4a2c-99b8-88b26f78ad81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTA4OTEsIm5iZiI6MTcyMTc5MDU5MSwicGF0aCI6Ii8xNzU1MTY1OTgvMzUxNTUxODIxLWY3OTc0MThkLTE3NjgtNGEyYy05OWI4LTg4YjI2Zjc4YWQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwMzA5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTY1ZDA0MDIyZjNiNzcxMWJkNDc4YmRlMmE0ZWNkMjlkMGI2Njg3ZjM1YzYyZjk0YzhkZTExOWU5NjFlZDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8ekDPEHoHEzLntMM3biaaptT4eOsLMlygRiT9nDYMG8)

我知道问题了，你的终端是波兰语，不是英语。
解决方法很简单，你先执行这个命令：
```
devil lang set english
```
再把所有进程关停：
```
killall -u $(whoami)
```
再重连ssh，删除之前部署的本仓库：
```
rm -rf ~/sing-box
```
然后重新部署一下应该就好了。

**Comment by k0baya** [comment]
已修复：[3ec714f](https://github.com/k0baya/sb-for-serv00/commit/3ec714fdcfbe7f80156c790d8342b79c77af5a64)

**Comment by flypig2025** [comment]
确实如此，谢谢大佬！
