### ISSUE TITLE
生成了配置文件，但连接无网络

### ISSUE THREAD

**Issue by sunboy0523** [k0baya/sb-for-serv00#5]
您好，按照说明部署，成功生成配置文件，但连接没网，请问是什么原因？谢谢

**Comment by k0baya** [comment]
因为来自 serv00 的 udp 流量被墙了。如果 trojan 也连不上就代表你所使用的 Server (s0、s1......s7)无法直连。

**Comment by sunboy0523** [comment]
> 因为来自 serv00 的 udp 流量被墙了。如果 trojan 也连不上就代表你所使用的 Server (s0、s1......s7)无法直连。

明白了，谢谢
