### ISSUE TITLE
一台机子始终卡住，没有list

### ISSUE THREAD

**Issue by wyhawk** [k0baya/sb-for-serv00#6]
![image](https://github.com/user-attachments/assets/23a77aa0-8383-4cec-bd5c-174e4c263d3b)
一直没有证书，自己下载放到singbox文件夹下面也没用

**Comment by k0baya** [comment]
你的操作失误导致进程达到上限，请把进程全杀了重新尝试。

**Comment by wyhawk** [comment]
试了几次都是这样，我同样的操作在另一台服务上就没问题

**Comment by k0baya** [comment]
如果其他另一台服务能够正常使用，而你截图的不行，那么你应该怀疑这台服务有问题。你可以去 [Serv00 Forum](https://forum.serv00.com/) 发帖求助其管理员。不是本仓库的问题，我无法提供帮助。
