### ISSUE TITLE
请问怎么修改config.js使配置地址由s*.serv00.com适配成web*.serv00.com

### ISSUE THREAD

**Issue by sunboy0523** [k0baya/sb-for-serv00#8]
您好，请问可以自己修改config.js使配置地址由s*.serv00.com适配成web*.serv00.com吗？谢谢

**Comment by k0baya** [comment]
参考：[UDP Responses are not received from client](https://forum.serv00.com/d/1101-udp-responses-are-not-received-from-client)

UDP 不支持。请考虑使用 [X-for-Serv00 Direct Branch](https://github.com/k0baya/X-for-serv00/tree/direct)

**Comment by sunboy0523** [comment]
> 参考：[UDP Responses are not received from client](https://forum.serv00.com/d/1101-udp-responses-are-not-received-from-client)
> 
> UDP 不支持。请考虑使用 [X-for-Serv00 Direct Branch](https://github.com/k0baya/X-for-serv00/tree/direct)

谢谢您每次都热心回复，我也用了您的X-for-Serv00 Direct Branch，对于被墙的s*.serv00.com，web*.serv00.com可以连通，但是速度很差。没有墙s*.serv00.com的服务器部署X-for-Serv00 Direct Branch速度也很慢，部署sb就很快。所以我想是不是hy2速度方面有优势，对于s*.serv00.com被墙，web*.serv00.com可以连通的服务器，如果可以sb地址部署成web*.serv00.com应该就节点就可以正常使用了，不过应该是实现不了。

**Comment by k0baya** [comment]
> > 参考：[UDP Responses are not received from client](https://forum.serv00.com/d/1101-udp-responses-are-not-received-from-client)
> > UDP 不支持。请考虑使用 [X-for-Serv00 Direct Branch](https://github.com/k0baya/X-for-serv00/tree/direct)
> 
> 谢谢您每次都热心回复，我也用了您的X-for-Serv00 Direct Branch，对于被墙的s*.serv00.com，web*.serv00.com可以连通，但是速度很差。没有墙s*.serv00.com的服务器部署X-for-Serv00 Direct Branch速度也很慢，部署sb就很快。所以我想是不是hy2速度方面有优势，对于s*.serv00.com被墙，web*.serv00.com可以连通的服务器，如果可以sb地址部署成web*.serv00.com应该就节点就可以正常使用了，不过应该是实现不了。

快，是因为 UDP。但是 UDP 只有 sX.serv00.com 这个地址能连通，TCP才能用另外两个地址。
